<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,17,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[2]=array(0,1,1,'5oqA5pyv5Y+C5pWw');
$cfg_Cs[3]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[4]=array(1,17,1,'TEVE57O75YiX');
$cfg_Cs[5]=array(1,17,1,'SElE57O75YiX');
$cfg_Cs[6]=array(1,17,1,'5peg5byA5YWz5pm66IO954Gv57O75YiX');
$cfg_Cs[7]=array(4,17,1,'5Yqo5oCB5qih57OK5pWw5o6n57O75YiX');
$cfg_Cs[8]=array(4,17,1,'5Yqo5oCB6Imy5rip5o6n5Yi257O75YiX');
$cfg_Cs[9]=array(4,17,1,'5Yqo5oCB54mp6IGU5o6n5Yi257O75YiX');
?>