<?php
$tmpdir = "c396fed0c4778790";
$vtime = 20180109;
$files[0] = "include/dedehtml2.class.php";
$files[1] = "include/dedehttpdown.class.php";
$files[2] = "include/dedetag.class.php";
$files[3] = "include/dedetemplate.class.php";
$files[4] = "dede/inc/inc_archives_functions.php";
$files[5] = "dede/templets/article_edit.htm";
$fileConut = 5;
$sqls[] = "20171228.sql";
$sqls[] = "20180104.sql";
$sqls[] = "20180107.sql";
$sqls[] = "20180109.sql";
?>