
<field:gongsi itemname="公司" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:gongsi>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:dianhua itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dianhua>

<field:youxiang itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:youxiang>

<field:liuyanneirong itemname="留言内容" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:liuyanneirong>
