
<field:ks_dz itemname="公司" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ks_dz>

<field:ks_tdmc itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ks_tdmc>

<field:ks_dh itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ks_dh>

<field:ks_yx itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ks_yx>
