
<field:ks_dz itemname="公司" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ks_dz>


<field:KS_tdmc itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:KS_tdmc>

<field:KS_dh itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:KS_dh>

<field:KS_yx itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:KS_yx>

<field:ks_ly itemname="留言" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ks_ly>


