<?php
$z[0]=Array("field","",397,416);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",417,443);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",483,512);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",551,609);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1549,1584);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\n        <div class=\"swiper-slide\" ><a href=\"[field:typelink/]\">[field:typename/]</a>\n          <div></div>\n        </div>\n        ",1866,2206);
$z[5][4]=array();
$z[5][4]['typeid']="1";
$z[5][4]['row']="8";
$z[5][4]['currentstyle']="<div class='swiper-slide vcurrclass'><a href='~typelink~' class='currclass'>~typename~</a> <div></div> </div>";
$z[6]=Array("channel","\n      <div class=\"swiper-slide\" ><a href=\"[field:typelink/]\">[field:typename/]</a></div>\n      ",2400,2648);
$z[6][4]=array();
$z[6][4]['row']="8";
$z[6][4]['currentstyle']="<div class='swiper-slide'><a href='~typelink~' class='currclass'>~typename~</a></div>";
$z[7]=Array("list","\n    <div class=\"wk-li\" onclick=\"window.location='[field:arcurl/]'\">\n      <div class=\"iwoo\">\n        <div class=\"wk-li1\"><img src=\"[field:litpic/]\" width=\"300\" height=\"209\"></div>\n        <div class=\"wk-li2\"></div>\n        <div class=\"wk-li3\">[field:title/]</div>\n      </div>\n    </div>\n    ",2827,3157);
$z[7][4]=array();
$z[7][4]['pagesize']="12";
$z[8]=Array("pagelist","",3279,3333);
$z[8][4]=array();
$z[8][4]['listitem']="info,pre,next";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",3424,3461);
$z[9][4]=array();
$z[9][4]['filename']="footer.htm";

?>